# Generated by Django 3.2.5 on 2022-03-09 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0002_auto_20220308_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='post',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
