# Generated by Django 3.2.5 on 2022-03-06 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.FileField(null=True, upload_to='picture/'),
        ),
    ]
