# Generated by Django 3.2.5 on 2022-03-09 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20220308_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='circle',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='circle_info',
            field=models.CharField(max_length=800, null=True),
        ),
    ]
