# Generated by Django 3.2.5 on 2022-03-11 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_website'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='picture',
            new_name='circle_picture',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='website',
            new_name='circle_website',
        ),
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.CharField(max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_picture',
            field=models.FileField(null=True, upload_to='picture/'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_website',
            field=models.URLField(null=True),
        ),
    ]
