# Generated by Django 3.2.5 on 2022-03-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('picture', models.FileField(null=True, upload_to='hall_picture/')),
                ('hall_info', models.CharField(max_length=1000, null=True)),
                ('industry_type', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=255)),
                ('business_hours', models.CharField(max_length=255)),
                ('capacity', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=32)),
                ('website', models.URLField(null=True)),
                ('region', models.CharField(max_length=32)),
                ('prefecture', models.CharField(max_length=32)),
                ('area', models.CharField(max_length=32)),
                ('is_able', models.BooleanField(default=True)),
                ('buss', models.CharField(max_length=255, null=True)),
                ('train', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'halls',
            },
        ),
    ]
