# Generated by Django 3.2.5 on 2022-03-11 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0002_rating_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hall',
            old_name='hall_info',
            new_name='info',
        ),
        migrations.AlterField(
            model_name='hall',
            name='capacity',
            field=models.PositiveIntegerField(),
        ),
    ]
