# Generated by Django 3.2.5 on 2022-03-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0003_auto_20220311_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hall',
            name='genre',
        ),
        migrations.AddField(
            model_name='review',
            name='rate',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hall',
            name='business_hours',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='body',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
