# Generated by Django 3.2.5 on 2022-03-13 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0004_auto_20220312_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hall',
            name='area',
        ),
    ]
